/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package leu_lab6;

import javax.swing.ImageIcon;

/**
 *
 * @author lifan
 */
public class Form1 extends javax.swing.JFrame {

    /**
     * Creates new form Form1
     */
    public Form1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame2 = new javax.swing.JFrame();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jRadioButton4 = new javax.swing.JRadioButton();
        jFrame3 = new javax.swing.JFrame();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jFrame4 = new javax.swing.JFrame();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jFrame5 = new javax.swing.JFrame();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jFrame2.setTitle("Вопрос№1 Детство");
        jFrame2.setMinimumSize(new java.awt.Dimension(400, 400));
        jFrame2.setResizable(false);
        jFrame2.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                jFrame2WindowClosing(evt);
            }
        });
        jFrame2.getContentPane().setLayout(null);

        jButton3.setText("Вперед");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jFrame2.getContentPane().add(jButton3);
        jButton3.setBounds(210, 310, 90, 23);

        jButton4.setText("Назад");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jFrame2.getContentPane().add(jButton4);
        jButton4.setBounds(40, 310, 80, 23);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Смотреть мультики");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jFrame2.getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(20, 100, 140, 23);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Бегать на улице");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jFrame2.getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(20, 140, 120, 23);

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("Играть с игрушками");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        jFrame2.getContentPane().add(jRadioButton3);
        jRadioButton3.setBounds(20, 180, 160, 23);

        jLabel1.setText("Вопрос: Чем нравилось заниматься в детстве?");
        jFrame2.getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 30, 280, 40);

        jLabel7.setText("Выбрано:");
        jFrame2.getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 240, 80, 30);
        jFrame2.getContentPane().add(jLabel8);
        jLabel8.setBounds(30, 250, 130, 30);
        jFrame2.getContentPane().add(jLabel11);
        jLabel11.setBounds(210, 100, 180, 150);

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setText("Читать книгу");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });
        jFrame2.getContentPane().add(jRadioButton4);
        jRadioButton4.setBounds(20, 210, 140, 23);

        jFrame2.setLocationRelativeTo(null);

        jFrame3.setTitle("Вопрос №2 Отрочество");
        jFrame3.setMinimumSize(new java.awt.Dimension(400, 400));
        jFrame3.setResizable(false);
        jFrame3.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                jFrame3WindowClosing(evt);
            }
        });
        jFrame3.getContentPane().setLayout(null);

        jButton5.setText("Вперед");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jFrame3.getContentPane().add(jButton5);
        jButton5.setBounds(200, 330, 80, 23);

        jButton6.setText("Назад");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jFrame3.getContentPane().add(jButton6);
        jButton6.setBounds(40, 330, 80, 23);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Физика", "Физкультура", "Математика", "Английский" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jFrame3.getContentPane().add(jComboBox1);
        jComboBox1.setBounds(40, 90, 150, 40);

        jLabel2.setText("Вопрос: Любимый предмет в школе?");
        jFrame3.getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 34, 220, 30);
        jFrame3.getContentPane().add(jLabel12);
        jLabel12.setBounds(220, 70, 160, 170);
        jFrame3.getContentPane().add(jLabel13);
        jLabel13.setBounds(30, 254, 160, 30);

        jFrame3.setLocationRelativeTo(null);

        jFrame4.setTitle("Вопрос№3 Юность");
        jFrame4.setMinimumSize(new java.awt.Dimension(400, 400));
        jFrame4.setResizable(false);
        jFrame4.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                jFrame4WindowClosing(evt);
            }
        });
        jFrame4.getContentPane().setLayout(null);

        jButton9.setText("Вперед");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jFrame4.getContentPane().add(jButton9);
        jButton9.setBounds(210, 330, 80, 23);

        jButton10.setText("Назад");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jFrame4.getContentPane().add(jButton10);
        jButton10.setBounds(50, 330, 80, 23);

        jCheckBox1.setText("Волейбол");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jFrame4.getContentPane().add(jCheckBox1);
        jCheckBox1.setBounds(50, 100, 120, 20);

        jCheckBox2.setText("Баскетбол");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });
        jFrame4.getContentPane().add(jCheckBox2);
        jCheckBox2.setBounds(50, 140, 120, 23);

        jCheckBox3.setText("Хоккей");
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });
        jFrame4.getContentPane().add(jCheckBox3);
        jCheckBox3.setBounds(50, 180, 120, 23);

        jLabel3.setText("Вопрос:Ваш любимый вид спорта?");
        jFrame4.getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 34, 270, 30);

        jLabel9.setText("Выбрано:");
        jFrame4.getContentPane().add(jLabel9);
        jLabel9.setBounds(30, 230, 70, 20);
        jFrame4.getContentPane().add(jLabel10);
        jLabel10.setBounds(90, 230, 120, 20);
        jFrame4.getContentPane().add(jLabel14);
        jLabel14.setBounds(180, 90, 200, 150);

        jFrame4.setLocationRelativeTo(null);

        jFrame5.setTitle("Результаты");
        jFrame5.setMinimumSize(new java.awt.Dimension(400, 400));
        jFrame5.setResizable(false);
        jFrame5.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                jFrame5WindowActivated(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                jFrame5WindowClosing(evt);
            }
        });
        jFrame5.getContentPane().setLayout(null);

        jButton7.setText("Назад");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jFrame5.getContentPane().add(jButton7);
        jButton7.setBounds(50, 330, 84, 23);

        jButton8.setText("Выход");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jFrame5.getContentPane().add(jButton8);
        jButton8.setBounds(290, 330, 85, 23);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jFrame5.getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(40, 90, 330, 200);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("Ваши результаты,спасибо!");
        jFrame5.getContentPane().add(jLabel6);
        jLabel6.setBounds(40, 30, 380, 40);

        jButton11.setText("О программе");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jFrame5.getContentPane().add(jButton11);
        jButton11.setBounds(240, 300, 140, 23);

        jFrame5.setLocationRelativeTo(null);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Добро Пожаловать!");
        setResizable(false);
        getContentPane().setLayout(null);

        jButton1.setText("Начать");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(48, 243, 80, 23);

        jButton2.setText("Выход");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(260, 243, 65, 23);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel4.setText("Анкета");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(120, 20, 190, 60);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Тема: Периоды жизни");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(100, 100, 280, 20);

        setSize(new java.awt.Dimension(424, 364));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
// Переход на 2 окно, кнопка «Вперед» 
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         this.setVisible(false); // Спрятать главное окно 1         
         jFrame2.setVisible(true); // Показать окно 2
    }//GEN-LAST:event_jButton1ActionPerformed

    // Переход на главное окно 1 из 2 окна, кнопка «Назад»
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        jFrame2.setVisible(false); // Спрятать окно 2
        this.setVisible(true); // Показать главное окно 1

    }//GEN-LAST:event_jButton4ActionPerformed
    // Переход на 3 окно из 2 окна, кнопка «Вперед»
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jFrame2.setVisible(false); // Спрятать окно 2
        jFrame3.setVisible(true); // Показать окно 3

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jFrame3WindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jFrame3WindowClosing
       System.exit(0);
    }//GEN-LAST:event_jFrame3WindowClosing

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        jFrame3.setVisible(false); // Спрятать окно 3
        jFrame4.setVisible(true); // Показать окно 4
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        jFrame3.setVisible(false); // Спрятать окно 3
        jFrame2.setVisible(true); // Показать окно 2
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jFrame4WindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jFrame4WindowClosing
        System.exit(0);
    }//GEN-LAST:event_jFrame4WindowClosing

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
      jFrame5.setVisible(false); // Спрятать окно 5
      jFrame4.setVisible(true); // Показать окно 4
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
      jFrame4.setVisible(false); // Спрятать окно 4
      jFrame5.setVisible(true); // Показать окно 5
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
       jFrame4.setVisible(false); // Спрятать окно 4
       jFrame3.setVisible(true); // Показать окно 3
                                            
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jFrame2WindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jFrame2WindowClosing
        System.exit(0);
    }//GEN-LAST:event_jFrame2WindowClosing

    private void jFrame5WindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jFrame5WindowClosing
       System.exit(0);
    }//GEN-LAST:event_jFrame5WindowClosing

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
    jLabel8.setText("Смотреть мультики");
            
        jLabel11.setIcon(new ImageIcon(getClass().getResource("1.1.jpg")));
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        switch (jComboBox1.getSelectedIndex()) {

            case 0:
                jLabel13.setText("Выбрано: Физика");
                jLabel12.setIcon(new ImageIcon(getClass().getResource("2.1.jpg")));
                break;
            case 1:
                jLabel13.setText("Выбрано: Физкультура");
                jLabel12.setIcon(new ImageIcon(getClass().getResource("2.2.jpg")));
                break;
            case 2:
                jLabel13.setText("Выбрано: Математика");
                jLabel12.setIcon(new ImageIcon(getClass().getResource("2.3.jpg")));
                break;
            case 3:
                jLabel13.setText("Выбрано: Англиский");
                jLabel12.setIcon(new ImageIcon(getClass().getResource("2.4.jpg")));
                break;
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jFrame5WindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jFrame5WindowActivated
        jTextArea1.setText(""); // Очистка компонента
        jTextArea1.append("Ваш выбор:" + "\n");
        jTextArea1.append("___________________" + "\n");
        jTextArea1.append("Занятие: " + jLabel8.getText().toString() + "\n");
        jTextArea1.append("Предмет: " + jComboBox1.getSelectedItem().toString() + "\n");
        jTextArea1.append("Спорт: " +jLabel10.getText().toString()  + "\n");
    
    
    }//GEN-LAST:event_jFrame5WindowActivated

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // Вызов окна «О программе»
        new NewJDialog(null, true).setVisible(true);

    }//GEN-LAST:event_jButton11ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        jLabel8.setText("Бегать на улице");
        
        jLabel11.setIcon(new ImageIcon(getClass().getResource("1.2.jpg")));
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        jLabel8.setText("Играть с игрушками");
        
        jLabel11.setIcon(new ImageIcon(getClass().getResource("1.3.jpg")));
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
         jLabel10.setText("Воллейбол");
        if (jCheckBox1.isSelected()) {
            jCheckBox2.setSelected(false);
            jCheckBox3.setSelected(false);
        }
        jLabel14.setIcon(new ImageIcon(getClass().getResource("3.1.jpg")));
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
            jLabel10.setText("Баскетбол");
        if (jCheckBox2.isSelected()) {
            jCheckBox1.setSelected(false);
            jCheckBox3.setSelected(false);
        }
        jLabel14.setIcon(new ImageIcon(getClass().getResource("3.2.jpg")));
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
             jLabel10.setText("Хоккей");
        if (jCheckBox3.isSelected()) {
            jCheckBox1.setSelected(false);
            jCheckBox2.setSelected(false);
            jLabel14.setIcon(new ImageIcon(getClass().getResource("3.3.jpg")));
        }
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        jLabel8.setText("Читать книжку");
       
       
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    

   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JFrame jFrame3;
    private javax.swing.JFrame jFrame4;
    private javax.swing.JFrame jFrame5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
